"""initial schema

Revision ID: 29e90e86f5f6
Revises: 
Create Date: 2026-07-09 18:01:38.213387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29e90e86f5f6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cost_matrix_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=True),
    sa.Column('costs', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('datasets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('n_rows', sa.Integer(), nullable=False),
    sa.Column('n_cols', sa.Integer(), nullable=False),
    sa.Column('label_col', sa.String(length=128), nullable=False),
    sa.Column('columns', sa.JSON(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analysis_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('dataset_id', sa.String(length=36), nullable=True),
    sa.Column('use_case', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('winner_model', sa.String(length=64), nullable=True),
    sa.Column('recommended_threshold', sa.Float(), nullable=True),
    sa.Column('reduction_pct', sa.Float(), nullable=True),
    sa.Column('runtime_sec', sa.Float(), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('error', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analysis_runs')
    op.drop_table('datasets')
    op.drop_table('cost_matrix_configs')
    # ### end Alembic commands ###
